{% set version = "24.11.0" %}

package:
  name: twisted
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/twisted/twisted-{{ version }}.tar.gz 
  sha256: 695d0556d5ec579dcc464d2856b634880ed1319f45b10d19043f2b57eb0115b5

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - ckeygen = twisted.conch.scripts.ckeygen:run
    - cftp = twisted.conch.scripts.cftp:run
    - conch = twisted.conch.scripts.conch:run
    - mailmail = twisted.mail.scripts.mailmail:run
    - pyhtmlizer = twisted.scripts.htmlizer:run
    - tkconch = twisted.conch.scripts.tkconch:run
    - trial = twisted.scripts.trial:run
    - twist = twisted.application.twist._twist:Twist.main
    - twistd = twisted.scripts.twistd:run
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling >=1.10.0
    - hatch-fancy-pypi-readme >=22.5.0
    - incremental >=24.7.0 
  run:
    - python
    - zope.interface >=5
    - constantly >=15.1
    - incremental >=24.7.0
    - automat >=24.8.0
    - hyperlink >=17.1.1
    - attrs >=22.2.0
    - typing_extensions >=4.2.0
    - twisted-iocpsupport >=1.0.2  # [win]
    - pywin32 !=226  # [win]
    # conch deps
    - appdirs >=1.4.0
    - bcrypt >=3.1.3
    - cryptography >=3.3
    # tls deps
    - idna >=2.4
    - pyopenssl >=21.0.0
    - service_identity >=18.1.0
  run_constrained:
    # Moved all the crypto and tls stuff under 'run'
    - pyserial >=3.0
    - h2 >=3.0,<5.0
    - priority >=1.1.0,<2.0

test:
  imports:
    - twisted
    - twisted._threads
    - twisted.application
    - twisted.application.runner
    - twisted.application.twist
    - twisted.conch
    - twisted.conch.client
    - twisted.conch.insults
    - twisted.conch.openssh_compat
    - twisted.conch.scripts
    - twisted.conch.ssh
    - twisted.conch.ui
    - twisted.cred
    - twisted.enterprise
    - twisted.internet
    - twisted.internet.iocpreactor  # [win]
    - twisted.logger
    - twisted.mail
    - twisted.mail.scripts
    - twisted.names
    - twisted.pair
    - twisted.persisted
    - twisted.plugins
    - twisted.positioning
    - twisted.protocols
    - twisted.protocols.haproxy
    - twisted.python
    - twisted.runner
    - twisted.scripts
    - twisted.spread
    - twisted.tap
    - twisted.trial
    - twisted.trial._dist
    - twisted.web
    - twisted.web._auth
    - twisted.words
    - twisted.words.im
    - twisted.words.protocols
    - twisted.words.protocols.jabber
    - twisted.words.xish
  requires:
    - pip
  commands:
    - pip check
    - ckeygen --help
    # https://twistedmatrix.com/trac/ticket/1679
    - cftp --help  # [not win]
    - conch --help  # [not win]
    # not sure how to test this one
    # - mailmail --help
    - pyhtmlizer --help
    # Requires $DISPLAY (xvfb-run?)
    - tkconch --help  # [win]
    - trial --help
    - twist --help
    - twistd --help

about:
  home: https://twisted.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: An event-based framework for internet applications, written in Python
  description: |
    Twisted is an event-based framework for internet applications, written in Python.
  doc_url: https://docs.twisted.org
  dev_url: https://github.com/twisted/twisted

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
