travis:
  secure:
    BINSTAR_TOKEN: ftngCDQROgESBwOLIDPMh7T04efVSqMXoBeMNFZML/cGFpe4vfQarVBWzNJ6tV/UtMWYWOWKetqz8kZyVu8WLsdPLnLCJzBVW3etkeSr79GzxlZHpv4UxM/cKZksbuy9kAyQbB3KfAIRVKh6XBZLx2xAowD1rXI3gWZ0H3tjavH8wDSIaodAClqo+3LdJrEDlKvsAMZnGEBZ/gbfsxZ4ItvJagTTzL7qN/gvxdI2kn6qwGvfGpUd/ftX4l6DRggt5w2UbCXQvPyevwtYZRpcL8g0Mf/XVFXh43sOghXZn8k2e/hkatnebB/aSJKQ8A6ANNEbPSFrF3dkkZiPSD0TOw8oR50e+c6BCrdpPf3pAfkmz88XDUQWYbTye43GTI8us7uBoUcWF8mKA1yDyt4jCSHm89H+0+1Kk0EtrYieARzMfhykkZ3Ff/MAZmt6rdyA3CrD05UoGE24WImG70zgAoFneVw7VwerounmJLFZzD+ruli7c6EgG5meCj4iaYOlqwRRgXewSqtnGNCiSpvxbs6qrLRJ/j6C3tK6bKiFkRPBesn7Xvm9T3G1aG73k0XjqJ9s9+XokjIAaUWTXcPIj90wRIbsNJb/N1bNOMSp8b6rnCH+oIS5HZFaSRdj18FcO3oVgyCOTRyuA3gGw6oVZAftk/ONQbry7MYGB4IzVP0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
